FROM node:21-bookworm
WORKDIR /app
COPY . .
RUN npm install && npm run build

FROM nginx:1.25.3
COPY --from=0 /app/nginx /etc/nginx/templates
COPY --from=0 /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
