version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    restart: always
    volumes:
      - .:/app
    environment:
      - NGINX_PORT=80
  ngrok:
    image: ngrok/ngrok:3
    restart: always
    command:
      - "http"
      - "--domain=xxx.ngrok.app"
      - "web:80"
    links:
      - web
    environment:
      - NGROK_AUTHTOKEN=
